### PR TITLE
Export the `findUnclosed` method

### PR DESCRIPTION
**Pull request by jantimon**
I would like to validate a html source string - however right now it is only possible to analyse a path.

This pull request turns the existing `findUnclosed` method in a public exported method which returns an array of error objects which can be used by other libraries.

This would also allow to add unit tests for findUnclosed.

### CODE REVIEW

**Comment by marcosbasualdo** [comment]
Hi Jan! Let me test this version, if it works well it our current implementations i'll definitely merge this pull request today.

Thank you for contributing!

**Comment by jantimon** [comment]
Cool thanks for the quick response :+1:

**Comment by jantimon** [comment]
is there anything I can help you with?

**Comment by marcosbasualdo** [comment]
Merged!

**Comment by jantimon** [comment]
Cool thanks

**Pull request merged**
